### ISSUE TITLE
single libapp.so found instead of 4 files

### ISSUE THREAD

**Issue by phanirithvij** [Rondalal/flutter_extractor#1]
I see a single `libapp.so` under `app/lib/arm64-v8a/` when using the latest flutter version `1.9.1.hotfix.6` instead of 4 files.
So I think the issue that you've mentioned in the blog post was implemented.
Do you mind a follow-up article?

**Comment by Rondalal** [comment]
Thanks for the note! I will check it out :)

**Edit** - It seems that you are right. [Since 1.7.8](https://github.com/flutter/engine/pull/9172) there is libapp.so that contains all the code that is AOT compiled.
However, from a very quick & dirty check that I've just made, it seems that EVERYTHING is heavily  obfuscated (seems they understood the benefits of [proguard](https://developer.android.com/studio/build/shrink-code)), and implemented this in Flutter as well.

I will take a further look, and see if there's something that can be done. 
Thanks for the update :+1:
